spring:
  application:
    name: 01_Training_Institute_Counsellor_Portal

  datasource:
    url: jdbc:mysql://localhost:3306/counsellor_db
    username: root
    password: aman1028

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181